spring:
  application:
    name: GaraseKu
  datasource:
    url: jdbc:postgresql://127.0.0.1:5880/garaseku-db
    username: garaseku-admin
    password: Garaseku5881
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
